/// Generated by Flutter GetX Starter on 2021-09-08 23:45
import 'package:get/get.dart';

import 'join_club_v2_logic.dart';

class JoinClubV2Binding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<JoinClubV2Logic>(
      () => JoinClubV2Logic(),
    );
  }
}