/// Generated by Flutter GetX Starter on 2021-09-15 13:16
import 'package:get/get.dart';

import 'item_question_dynamic_logic.dart';

class ItemQuestionDynamicBinding extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut<ItemQuestionDynamicLogic>(
      () => ItemQuestionDynamicLogic(),
    );
  }
}