/// Generated by Flutter GetX Starter on 2021-09-15 13:16
import 'package:get/get.dart';


class ItemQuestionDynamicLogic extends GetxController {

  @override
  void onInit() {
    // TODO: implement onInit
    super.onInit();
  }

  @override
  void onReady() {
    // TODO: implement onReady
    super.onReady();
  }

  @override
  void onClose() {
    // TODO: implement onClose
    super.onClose();
  }
}